apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::593331310640:role/udacity-node-group
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::593331310640:role/eks-CodeBuildServiceRole
      username: codebuild-eks
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::593331310640:user/github-action-user
      username: github-action-role
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::593331310640:role/udacity-node-group\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n- rolearn: arn:aws:iam::{$AWS_ACCOUNT_ID}:role/eks-CodeBuildServiceRole\n  username: codebuild-eks\n  groups:\n    - system:masters\n","mapUsers":"- userarn: arn:aws:iam::593331310640:user/github-action-user\n  username: github-action-role\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-08-29T03:05:53Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"2773","uid":"62a19ddb-86b7-4337-b56c-5ccfcb512f0a"}}
  creationTimestamp: "2024-08-29T03:05:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "63773"
  uid: 62a19ddb-86b7-4337-b56c-5ccfcb512f0a
